name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# Add permissions configuration
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Inno Setup
      run: |
        $url = "https://jrsoftware.org/download.php/is.exe"
        $output = "is.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath "is.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait
        Remove-Item $output
        if (-not (Test-Path "C:\Program Files (x86)\Inno Setup 6\ISCC.exe")) {
          Write-Host "Inno Setup installation failed"
          exit 1
        }
        Write-Host "Inno Setup installed successfully"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install numpy==1.24.3
        pip install pandas==1.3.0
        pip install openpyxl==3.0.7
        pip install pywin32==310
        pip install packaging==21.0
        pip install matplotlib==3.5.0
        pip install PyQt6==6.9.0 PyQt6-Qt6==6.9.0 PyQt6-sip==13.10.0
        pip install requests==2.31.0
        pip install pyinstaller==6.13.0
    
    - name: Debug - Show Python Environment
      run: |
        python --version
        pip --version
        pip list
        echo "=== Checking Dependencies ==="
        python -c "import numpy; print('numpy version:', numpy.__version__)"
        python -c "import PyQt6; print('PyQt6 available')"
        python -c "import PyQt6.QtCore; print('QtCore available')"
        python -c "import PyQt6.QtWidgets; print('QtWidgets available')"
        python -c "import matplotlib; print('matplotlib available')"
        python -c "import pandas; print('pandas available')"
        python -c "import openpyxl; print('openpyxl available')"
    
    - name: Debug - Check Inno Setup Installation
      run: |
        if (Test-Path "C:\Program Files (x86)\Inno Setup 6\ISCC.exe") {
          Write-Host "Inno Setup is installed correctly"
          try {
            $output = & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /? 2>&1 | Out-String
            Write-Host "Inno Setup help output:"
            Write-Host $output
            if ($output -match "Inno Setup (\d+)") {
              Write-Host "Inno Setup version: $($matches[1])"
            } else {
              Write-Host "Could not extract version number, but Inno Setup is installed"
            }
          } catch {
            Write-Host "Error checking Inno Setup version: $_"
            Write-Host "Inno Setup is still installed and available for use"
          }
        } else {
          Write-Host "Inno Setup is not installed correctly"
          exit 1
        }
    
    - name: Update version
      shell: pwsh
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
        Write-Host "Setting version to: $version"
        $content = Get-Content -Path "src/utils/version.py" -Raw
        $pattern = '__version__ = ".*"'
        $replacement = "__version__ = `"$version`""
        $content = $content -replace $pattern, $replacement
        Set-Content -Path "src/utils/version.py" -Value $content
        Write-Host "Updated version.py content:"
        Get-Content -Path "src/utils/version.py"
    
    - name: Debug - Show Installed Packages
      run: |
        echo "=== Installed Packages ==="
        pip list
        echo "=== Package Details ==="
        pip show PyQt6
        pip show PyQt6-Qt6
        pip show PyQt6-sip
        pip show matplotlib
        pip show pandas
        pip show openpyxl
    
    - name: Debug - Check Project Structure
      run: |
        echo "=== Project Structure ==="
        echo "Current directory: $PWD"
        echo ""
        echo "Root directory contents:"
        Get-ChildItem | ForEach-Object {
          echo "  $($_.Name)"
        }
        echo ""
        echo "Src directory contents:"
        Get-ChildItem -Path "src" | ForEach-Object {
          echo "  $($_.Name)"
        }
        echo ""
        echo "Hook files:"
        Get-ChildItem -Path "." -Filter "hook-*.py" | ForEach-Object {
          echo "  $($_.Name)"
        }
        echo ""
        echo "=== End Project Structure ==="
    
    - name: Build executable
      run: python build.py --version ${{ github.ref_name }}
    
    - name: Debug - Show Build Output
      run: |
        echo "=== Build Output Debug Information ==="
        echo "Current directory: $PWD"
        echo ""
        echo "Output directory contents:"
        Get-ChildItem -Path "Output" -Recurse | ForEach-Object {
          if ($_.Name -match "DailyRegister_Setup_v.*\.exe") {
            echo "  $($_.FullName)"
            echo "    >>> This is the installer we're looking for <<<"
          } else {
            echo "  $($_.FullName)"
          }
        }
        echo ""
        echo "Dist directory contents:"
        Get-ChildItem -Path "dist" -Recurse | ForEach-Object {
          echo "  $($_.FullName)"
        }
        echo ""
        echo "Build directory contents:"
        Get-ChildItem -Path "build" -Recurse | ForEach-Object {
          echo "  $($_.FullName)"
        }
        echo ""
        echo "=== End Debug Information ==="
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Output/DailyRegister_Setup_${{ github.ref_name }}.exe
        asset_name: DailyRegister_Setup_${{ github.ref_name }}.exe
        asset_content_type: application/octet-stream 